version: '3'

tasks:
  install:
    desc: Install or update project dependencies.
    cmd: uv sync

  test:
    desc: Run tests in parallel and generate a coverage report.
    cmds:
      - task: install
      - uv run pytest --numprocesses=auto --cov=. --cov-report=html --cov-report=xml --cov-report=term src/
    silent: false

  lint:
    desc: Run static analysis tools (type checking and linting/fixing).
    cmds:
      - task: install
      - task: ty
      - task: ruff-fix
    silent: false

  ty:
    desc: Run type checking with Typer.
    cmd: uv tool run --from ty ty check

  ruff-fix:
    desc: Run Ruff to check, fix, and sort imports.
    cmds:
      - uv tool run --from ruff ruff format .
      - uv tool run --from ruff ruff check . --fix
    silent: false

  docs-build:
    desc: Build the documentation site.
    cmd: uv tool run --from mkdocs --with mkdocs-material --with 'mkdocstrings[python]' mkdocs build -c

  docs-serve:
    desc: Serve the documentation locally.
    cmd: uv tool run --from mkdocs --with mkdocs-material --with 'mkdocstrings[python]' mkdocs serve

  docs-deploy:
    desc: Deploy the documentation to GitHub Pages.
    cmd: uv tool run --from mkdocs --with mkdocs-material --with 'mkdocstrings[python]' mkdocs gh-deploy --force

  default:
    desc: Run all quality checks (lint and test).
    cmds:
      - task: lint
      # - task: test
      - task: docs-build
    silent: false